server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloudinary:
    cloud_name: {your cloud name}
    api_key: {your api key}
    api_secret: {your secret}
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    org.springframework.core.env: DEBUG

jwt:
  secret: secretKeyToGenJWTs 
  expiration: 86400000