# server:
#   port: 8080
#   servlet:
#     context-path: /api

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/university_db
#     username: root
#     password: 1234
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect

#   thymeleaf:
#     prefix: classpath:/templates/
#     suffix: .html
#     mode: HTML5
#     cache: false

#   servlet:
#     multipart:
#       max-file-size: 20MB
#       max-request-size: 20MB

#   cloudinary:
#     cloud_name: dlt5vrlat
#     api_key: 517399772578689
#     api_secret: Gab61TmwAxzGAzJg2DwLckR_7Js

# logging:
#   level:
#     org.springframework: INFO
#     com.example: DEBUG

# jwt:
#   secret: secretKeyToGenJWTs
#   expiration: 86400000 # 1 ngày (millisecond)

# server:
#   port: 8080
#   servlet:
#     context-path: /api

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/university_db
#     username: root
#     password: 1234
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   thymeleaf:
#     prefix: classpath:/templates/
#     suffix: .html
#     mode: HTML5
#     cache: false
#   servlet:
#     multipart:
#       max-file-size: 20MB
#       max-request-size: 20MB

# spring:
#   cloudinary:
#     cloud_name: dlt5vrlat
#     api_key: 517399772578689
#     api_secret: Gab61TmwAxzGAzJg2DwLckR_7Js

# logging:
#   level:
#     org.springframework: INFO
#     com.example: DEBUG
#     org.springframework.core.env: DEBUG

# jwt:
#   secret: secretKeyToGenJWTs
#   expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloudinary:
    cloud_name: dlt5vrlat
    api_key: 517399772578689
    api_secret: Gab61TmwAxzGAzJg2DwLckR_7Js

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    org.springframework.core.env: DEBUG

jwt:
  secret: secretKeyToGenJWTs 
  expiration: 86400000